### PR TITLE
fixed error when shutting down provider

### PR DESCRIPTION
**Pull request by zdanek**
fixed error when shutting down provider with manager not found in managers collection

### CODE REVIEW

**Comment by terracotta-org** [comment]
Can one of the admins verify this patch?

**Comment by alexsnaps** [comment]
@zdanek I wonder if this shouldn't throw an `IllegalArgumentException` or something... Can you share you ended up hitting that problem?

**Comment by zdanek** [comment]
As simple as that:

        Configuration configuration = new Configuration();
        CacheManager manager = new CacheManager(configuration);
        JCacheCachingProvider provider = new JCacheCachingProvider();
        URI uri = null;
        Properties props = new Properties();
        JCacheManager jCacheManager = new JCacheManager(provider, manager, uri, props);
        jCacheManager.close();

I *KNOW* that it should be done otherwise, with
Caching.getCachingProvider().getCacheManager()

But currently I'm forced to create a runtime configuration and that's why I must instantiate my own CacheManager and then JCacheManager. I'm not using JCacheCachingProvider at all.

Current implementation of JSR107 for EhCache doesn't allow passing a runtime config for CacheManager. Only XML is allowed.

**Comment by ljacomet** [comment]
test this please

**Comment by ljacomet** [comment]
test this please

**Comment by alexsnaps** [comment]
Merged

**Pull request closed without merging**
